import React from 'react';
import {
  Folder, Box, Zap, Sparkles, MessageCircle, LayoutGrid,
  Utensils, Home, User, Clock, Sun, Gamepad2, Shirt,
  Music, Book, Car, Heart, Smile, Cat, Dog, Flower,
  Apple, Briefcase, Calculator, Camera, Cloud, Coffee,
  Drumstick, Fish, Flag, Ghost, Gift, Globe, Hammer,
  Headphones, Key, Lightbulb, Map, Moon, Palette,
  Phone, Pizza, Plane, Scissors, Snowflake, Star,
  Trophy, Truck, Umbrella, Video, Watch, Wrench,
  Baby, Bath, Bed, Bell, Bike, Bird, Bone, Bus,
  Cake, Candy, CloudRain, Coins, Crown, DollarSign,
  Eye, Feather, Flame, Footprints, Glasses, GraduationCap,
  Hand, HeartPulse, Hourglass, Image, Leaf, Library,
  Lock, Mail, Mic, Mountain, Navigation, Package,
  Paintbrush, PartyPopper, PenTool, Rocket,
  Search, Ship, ShoppingBag, ShoppingCart, Shovel,
  Skull, Smartphone, Speaker, Stethoscope, Store,
  Tent, Ticket, Timer, Train, TreePine, Tv,
  Wallet, Wifi, Accessibility
} from 'lucide-react';

export const ICON_MAP: Record<string, React.ElementType> = {
  'folder': Folder,
  'things': Box,
  'actions': Zap,
  'desc': Sparkles,
  'social': MessageCircle,
  'other': LayoutGrid,
  'food': Utensils,
  'places': Home,
  'people': User,
  'time': Clock,
  'nature': Sun,
  'play': Gamepad2,
  'clothes': Shirt,
  'music': Music,
  'school': Book,
  'vehicles': Car,
  'feelings': Heart,
  'happy': Smile,
  'cat': Cat,
  'dog': Dog,
  'flower': Flower,
  'apple': Apple,
  'work': Briefcase,
  'math': Calculator,
  'photo': Camera,
  'weather': Cloud,
  'drink': Coffee,
  'meat': Drumstick,
  'fish': Fish,
  'flag': Flag,
  'scary': Ghost,
  'gift': Gift,
  'world': Globe,
  'build': Hammer,
  'listen': Headphones,
  'key': Key,
  'idea': Lightbulb,
  'map': Map,
  'night': Moon,
  'art': Palette,
  'call': Phone,
  'pizza': Pizza,
  'travel': Plane,
  'craft': Scissors,
  'snow': Snowflake,
  'star': Star,
  'win': Trophy,
  'truck': Truck,
  'rain': Umbrella,
  'watch': Video,
  'fix': Wrench,
  'baby': Baby,
  'bath': Bath,
  'bed': Bed,
  'bell': Bell,
  'bike': Bike,
  'bird': Bird,
  'bone': Bone,
  'bus': Bus,
  'cake': Cake,
  'candy': Candy,
  'rainy': CloudRain,
  'coins': Coins,
  'crown': Crown,
  'money': DollarSign,
  'eye': Eye,
  'feather': Feather,
  'fire': Flame,
  'walk': Footprints,
  'glasses': Glasses,
  'grad': GraduationCap,
  'hand': Hand,
  'health': HeartPulse,
  'wait': Hourglass,
  'picture': Image,
  'leaf': Leaf,
  'library': Library,
  'lock': Lock,
  'mail': Mail,
  'speak': Mic,
  'mountain': Mountain,
  'nav': Navigation,
  'package': Package,
  'paint': Paintbrush,
  'party': PartyPopper,
  'draw': PenTool,
  'rocket': Rocket,
  'search': Search,
  'ship': Ship,
  'shop': ShoppingBag,
  'cart': ShoppingCart,
  'dig': Shovel,
  'danger': Skull,
  'phone': Smartphone,
  'loud': Speaker,
  'doctor': Stethoscope,
  'store': Store,
  'camp': Tent,
  'ticket': Ticket,
  'timer': Timer,
  'train': Train,
  'tree': TreePine,
  'tv': Tv,
  'wallet': Wallet,
  'wifi': Wifi,
  'wheelchair': Accessibility
};

export const getIconComponent = (iconName?: string) => {
  if (!iconName || !ICON_MAP[iconName]) return Folder;
  return ICON_MAP[iconName];
};

export const getAvailableIcons = () => Object.keys(ICON_MAP);